### ISSUE TITLE
FINOS TSC Elections and Formation - Request for Comments [RFC]

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/community#162] opened 2022-02-21 14:29 UTC
Last month a [Request for Comments (RFC) was raised](https://github.com/finos/community/issues/153) regarding the formation of a Technical Steering Committee (TSC). In brief, The TSC would support the FINOS Governing Body (GB) and FINOS Team, by creating a group that focuses on the ‘solution space’ giving direct and meaningful support to the FINOS portfolio of projects.

The initial RFC was well received, with 6x +1s, 12x positive comments, and 5x people indicating that they would be interested in joining the TSC. This RFC provides more detail, outlining the process for assembling the TSC, its composition and the voting required to achieve that initial composition.

Once again, this process draws on prior art, having considered the similar committees within similar organisations (e.g. [CNCF TOC](https://github.com/cncf/toc), [Hyperledger TSC](https://tsc.hyperledger.org/), [LFN TAB](https://linuxfoundation.org/technical-advisory-board/) …)

For the TSC to be a success, we need members that are:

- Engaged, and active - committing time to both formal meetings and various other activities. They should actively engage with FINOS Projects.
- Knowledgeable and professional
- Able to leverage their organisation
- Neutral - first-and-foremost representing the needs of the members

In other organisations it is common for the TSC (or similar) to have seats allocated to different classes of vote. This reflects the [FINOS GB](https://www.finos.org/governing-board), where the different membership levels (platinum, gold, silver) have different levels of elected representation. It is proposed that with the TSC we do the same.

The TSC would have 13 seats, each having a two year term
 - 6 elected by the FINOS Governing Body 
 - 7 elected by the Community

Nominations would be encouraged from both the community and the GB. Nominees must either be active contributors (as defined by LFX Insights) or an employee of a member organisation. FINOS already has a process for collecting nominations, and tallying votes (which is used for GB representation), we would use the same process and mechanisms for the TSC.

The voting process would have two rounds:
 - The FINOS GB vote would be conducted and 6 individuals would be elected
 - Following this, of the remaining candidates, a community vote (involving active contributors) would be held, with the 7 remaining seats filled.

Following the voting process, the TSC would meet to elect a Chair, with the initial meetings focussed on elaborating the TSC responsibilities and formalising this as part of the overall [FINOS Governance](https://www.finos.org/governance).

After community consultation, the goal is to bring a proposal to the Membership & Governance Committee (a group that assists the GB in governance related matters) in March and the Governing Body in April.

Please provide your feedback below!

**Comment by mindthegab** [comment] 2022-04-14 18:34
Absolutely @jonfreedman - I think cross-industry representation would be beneficial.

Given we haven't gotten yet a lot of feedback on this issue, but we have several topics which would make valuable TSC topics (and help grease the wheels), after discussing with @ColinEberhardt and @jgavronsky I am inclined to propose this approach to the upcoming 4/20 Governing Board meeting:

- Use Q2 to create a "pilot" TSC group, chaired by @ColinEberhardt, with 5/10 volunteers across our membership and community 
- The goal would be to 1. make sure we enough representations from financial institutions 2. create an, initially advisory, committee that can work on 3/4 concrete questions in Q2 and come back with a recommendation to the Governing Board in July. 
- If pilot is successful, ratify the creation of the committee in July and proceed with the formal elections / appointments / etc. 

Just to make sure I haven't forgotten anyone, current volunteers [gathered in the other issue (https://github.com/finos/community/issues/153) (of course pending approvals) are:

- @ColinEberhardt 
- @jonfreedman 
- @brunodom (Intel)
- @peter-thomas-db (Deutsche Bank)
- @stephengoldbaum (Morgan Stanley)
- @opoupeney (Symphony)
- @cdeliaRH (Red Hat)
- @rikoe (Adaptive)
- @martin-traverse (Accenture)

If you are interested in volunteering for this pilot phase (**please note: FINOS will support, but we expect active work to be required here!**) please post a comment under this issue.

**Comment by martin-traverse** [comment] 2022-04-14 18:55
Good to see this moving ahead, I'm very happy to be included in a pilot as suggested.

**Comment by mindthegab** [comment] 2022-04-23 00:28
Per my last comment, I'm happy to confirm, the Governing Board approved the creation of a "pilot TSC" with a limited number of folks (and strong end user representation, i.e. financial institutions) to operate of the rest of 2022 and bring back advice the board at the Q3 and Q4 GB meetings.

@ColinEberhardt has been selected as pilot TSC Chair and will work with the Governing Board on the selection of volunteer candidates. 

Please add a comment below if you'd like to volunteer or feel free to reach out directly to @ColinEberhardt and me.

Thanks for your support folks, this is an exciting evolution in our Community.

**Comment by jonfreedman** [comment] 2022-04-23 17:48
Thank you Gab and Colin, as per my previous comment I'm keen to be of help if I can, I've asked our compliance team to review accordingly

**Comment by peterrhysthomas** [comment] 2022-04-25 07:54
I am keen to help too

**Comment by ColinEberhardt** [comment] 2022-04-25 08:09
Thanks @peterrhysthomas and @jonfreedman - I'll be in touch with both of you shortly.

**Comment by opoupeney** [comment] 2022-04-25 13:06
Thanks Gab and Colin, confirming I am ready to help as well.

**Comment by mindthegab** [comment] 2022-04-27 19:36
@ColinEberhardt FYI we also received the candidacy of @beekemarie (Goldman Sachs) and Veronica Quinones (BMO).

**Comment by mindthegab** [comment] 2022-05-04 15:19
@dovops and @bingenito confirmed that @stephengoldbaum is Morgan Stanley's candidate for the Technical Steering Committee.

**Comment by ColinEberhardt** [comment] 2022-05-11 13:36
Hi @vquinon thanks for your interest, much appreciated.

**Comment by mindthegab** [comment] 2022-06-06 17:15
@ColinEberhardt Thanks for all the work on setting up the committee. Once you have next steps/infra/collaboration channels created (I know you're working with @maoo here), it would be great to post a closing update here and close this issue.

Super excited of this new and very important body being created! Looking forward to partnering with all of you.

**Comment by robmoffat** [comment] 2022-10-12 09:57
@ColinEberhardt well done on setting up the TSC!  

Since we now have https://github.com/finos/technical-steering-committee I would expect further TSC-related issues to be raised there.

Any further issues on the community project, such as project onboarding, we will clearly label with the `ready-for-tsc` flag.

Closing for now - please re-open if you think any further work needs doing on this.

**Closed by robmoffat** 2022-10-12 09:57 UTC
Labels: rfc
