### ISSUE TITLE
Morph Hadouken Program to top level projects and discontinue PMC

### ISSUE THREAD

**Issue by mindthegab** [finos/community#43] opened 2020-05-15 00:39 UTC
Per VOTE on [Hadouken PMC list](https://groups.google.com/a/finos.org/forum/#!topic/hadouken-pmc/NbRES3zdBkQ), the PMC has decided to disband and select projects to continue as Top-Level /cc @finos/hadouken-pmc @chuckdoerr

So please execute on the following tasks:

1. @aitana16 I don't think there was a recurring PMC meeting but please add notices in the Wiki regarding the program deprecation
2. @maoo Move the following projects at top level, fo 
  - [python adapter](https://github.com/HadoukenIO/python-adapter): register as top-level project (don't think it's in metadata), move to main FINOS github org and rename repo to "openfin-python-adapter". Please communicate directly with the team on the repo, or via PMC list if needed.
  - Openfin React Hooks: already living in the main FINOS org, so no change needed here other than metadata 
3. Archive all other Hadouken the other repositories (in github) and transition remaining Projects/Working groups to "Archived"  lifecycle stage. Check with me for any doubts.

**Comment by aitana16** [comment] 2020-05-15 01:45
@mindthegab done, see the [Hadouken program homepage](https://finosfoundation.atlassian.net/wiki/spaces/HAD/overview?homepageId=22970381) and the [Hadouken PMC homepage](https://finosfoundation.atlassian.net/wiki/spaces/HAD/pages/40468497/PMC)

**Comment by maoo** [comment] 2020-05-15 08:34
Based on the issue description, this is the list of action I understand is needed to be taken; @mindthegab please 👍 or quote reply the specific items.

1. Hadouken Application Templates - archive project
2. app-template - archive and transfer repo to github.com/finos
3. Desktop Services - archive project
4. service-utils - archive and transfer repo to github.com/finos
5. Hadouken - archive project
6. core, js-adapter, fdc3-service, fdc3-sender - archive and transfer repos to github.com/finos
7. symphony-of - transfer (archived) repo to github.com/finos
8. layouts-service, layouts-tabstrip, service-tooling - transfer (archived) repos to github.com/finos
9. Hadouken Notifications Service - archive project
10. notifications-service - archive and transfer repos to github.com/finos
11. Create "Python Adapter" project on github.com/finos (transfer repo from https://github.com/HadoukenIO/python-adapter)
12. Zero Downtime Trading Demo - archive project
13. zero-downtime-trading-web-ux - archive and transfer repos to github.com/finos

**Comment by mindthegab** [comment] 2020-05-21 20:50
Not sure what was unclear in the original description. 

It was implicit that I would leave all archived projects in the current org and move only the python adapter renaming it with the openfin- prefix to avoid naming clashes. 

Any reason to go to the trouble of moving some archive repos? (and leave some in the current org) What was the rationale?

**Comment by maoo** [comment] 2020-05-22 01:03
After our latest phone call, we agreed on the following.

1. Hadouken Application Templates - archive project
2. app-template - archive repo
3. Desktop Services - archive project
4. service-utils - archive repo
5. Hadouken - archive project
6. core, js-adapter, fdc3-service, fdc3-sender - archive repo
7. Hadouken Notifications Service - archive project
8. notifications-service - archive repo
9. Transfer repo from https://github.com/HadoukenIO/python-adapter to github.com/finos and rename to "openfin-python-adapter"
10. Zero Downtime Trading Demo - archive project
11. zero-downtime-trading-web-ux - archive repo

Will update the issue when all done. TY!

**Comment by maoo** [comment] 2020-05-22 14:27
I see that some repos on https://github.com/HadoukenIO are still active, I'd suggest to get in touch with developers. WDYT @mindthegab ?

**Comment by maoo** [comment] 2020-05-22 16:46
Let's archive projects but keep active repos as they are, then follow up via email with OpenFin.

**Comment by maoo** [comment] 2020-05-25 10:01
Done:
- Hadouken Application Templates - archive project
- app-template - archive repo
- Desktop Services - archive project
- service-utils - archive repo
- Hadouken - archive project
- core, js-adapter, fdc3-sender - archive repo
- Hadouken Notifications Service - archive project
- notifications-service - archive repo
Transfer repo from https://github.com/HadoukenIO/python-adapter to github.com/finos and rename to "openfin-python-adapter"
- Zero Downtime Trading Demo - archive project
- zero-downtime-trading-web-ux - archive repo
- service-signal, layouts-tabstrip, dotnet-notifications-service-demo, dotnet-fdc3-client, dotnet-notification-service-client, dotnet-fdc3-demo - archive repo

Not Done (since repositories are still active):
- fdc3-service, service-tooling, service-async, service-config - archive repos

@mindthegab - please review

It will take 2/3 days for changes to propagate; at that point we can close the issue (if no changes are requested)

**Comment by maoo** [comment] 2020-06-02 18:56
The Hadouken dev team have confirmed that by Friday the remaining repos can be archived.

I'll proceed on Friday and update this issue.

**Comment by maoo** [comment] 2020-06-05 06:16
All done, hadouken team notified!

**Closed by maoo** 2020-06-05 06:16 UTC
